### ISSUE TITLE
ios persent>50有问题

### ISSUE THREAD

**Issue by y0320li** [glangzh/wx-progress#1]
rightStyle_mask(){
        const { wxc_radius, wxc_Color } = this;
        return {
            height: `${wxc_radius * 2}px`,
            width: `${wxc_radius}px`,
            backgroundColor: wxc_color,
            borderTopRightRadius: `${wxc_radius}px`,
            borderBottomRightRadius: `${wxc_radius}px`
        }
      },

wxc_Color这地方写错了，应该是wxc_color,要不然ios那边mask没有作用

**Comment by glangzh** [comment]
已修复，谢谢提醒！
